### ISSUE TITLE
Allow custom chunk names

### ISSUE THREAD

**Issue by defrex** [faceyspacey/babel-plugin-universal-import#10]
I'd like to be able to customize my chunk names so I can bundle similar pages into a single chunk. This is doable without the babel plugin, but it's a little inelegant.
```js
const LoginPage = universal(() => import(/* webpackChunkName: "app" */ 'components/pages/login'), { chunkName: 'app' })
const DashboardPage = universal(() => import(/* webpackChunkName: "app" */ 'components/pages/dashboard'), { chunkName: 'app' })
```

Thoughts?

**Comment by faceyspacey** [comment]
PR :) ...it's low priority cuz it is doable without it. but being able to use the magic comment to customize in conjunction with the babel plugin has been something I've wanted.

Question: how do u know about using the `chunkName` as an option? I removed it from the docs a month ago. You were using this before then too?? ...cuz I'm thinking I should likely put it back in the docs.

**Comment by defrex** [comment]
This blog post tipped me off to it's existence:
https://medium.com/faceyspacey/how-to-use-webpacks-new-magic-comment-feature-with-react-universal-component-ssr-a38fd3e296a

Then when I didn't see it in the docs I read through the source to confirm it was still operational. It wasn't until afterwards that I realized `babel-plugin-universal-import` was tearing it down on me.

Even now I'm still getting the loading state during SSR which I wasn't with the babel plugin. I assume it's something to do with missing options passed to `universal`, since that's what the plugin is doing, for the most part.

Thanks for all the great work BTW!

**Comment by faceyspacey** [comment]
np. pass the `resolve` option. if ur server is babel, then pass the `path` option *too*. just as shown in the readme here, but as a plain option in the 2nd arg to `universal`. that's probably why SSR isnt working.

**Comment by defrex** [comment]
Confirmed working like so:
```js
const DashboardPage = universal(() => import(/* webpackChunkName: "app" */ 'components/pages/dashboard'), {
  resolve: () => require.resolveWeak('components/pages/dashboard'),
  chunkName: 'app',
})
```
It's a little unwieldy though. I might look into writing that PR, see how complex it is. Any tips?

**Comment by faceyspacey** [comment]
Search the code for the word "comment" and you will see how adding/removing comments is dealt with.

If u haven't made a babel plugin before read james kyle'a guide. It's not that hard. And u will come away feeling like a Jedi.

**Comment by faceyspacey** [comment]
doing some cleanup. gonna close this out as the PR references it. we'll incorporate this stuff in the next major release.
