### ISSUE TITLE
chunks are nested following the magic comment

### ISSUE THREAD

**Issue by salzhrani** [faceyspacey/babel-plugin-universal-import#11]
We rely on a flat build folder, currently the plugin includes folder separators which causes the written chunks to be nested.
if OK, I would like to make a PR to replace or escape the `/` for chunks to remain flat

**Comment by faceyspacey** [comment]
Sure, but it would have to be as an option. And not the default option.

**Comment by salzhrani** [comment]
I am thinking
```
["universal-import", {
      "flatten": true //or
      "flatten": '-'
    }]
```

**Comment by faceyspacey** [comment]
looks good!

**Comment by faceyspacey** [comment]
gonna close this. we got it recorded in your PR. when i get back to around to the next major release, i'll incorporate this.
