### ISSUE TITLE
setHasPlugin function catch a MODULE_NOT_FOUND error when use universalImport on server

### ISSUE THREAD

**Issue by urjustsocool** [faceyspacey/babel-plugin-universal-import#140]
Environment: Node v12.9.1
I got a problem when I use this plugin in @babel/register:
I want to use chunkName this plugin generate, but as what universal component did, only `setHasBabelPlugin` has been called, can generated chunkName been used.

![image](https://user-images.githubusercontent.com/32243277/95669089-230a6c00-0baf-11eb-9f84-6e03d9b8c2a2.png)

This picture shows that `require("babel-plugin-universal-import/universalImport")` is required before `require("react-universal-component")`, So the `setHasPlugin` function catch an Error: `{"code":"MODULE_NOT_FOUND","requireStack":[]}`.  As a result, I can't have the right chunkName been involved in.

my @babel/register config below:

```
plugins: [
            require.resolve('@babel/plugin-syntax-dynamic-import'),
            [require.resolve('babel-plugin-universal-import'), {
                        babelServer: true
           }],
]
```

**Comment by ScriptedAlchemy** [comment]
Move to loadable components. I don't have any other maintainers who are willing to support this project unfortunately

**Comment by urjustsocool** [comment]
Got it, thanks anyway.
