### ISSUE TITLE
Trying to make it work with babel-preset-env

### ISSUE THREAD

**Issue by luisherranz** [faceyspacey/babel-plugin-universal-import#17]
Babel-env let you determine the plugins and polyfills you need based on your targeted browser, which is really cool
https://github.com/babel/babel/tree/master/experimental/babel-preset-env

But I'm having a hard time trying to make it work with `universal-import`.

If I use a conventional `.babelrc` file like this, it works perfectly:
```javascript
{ 
  "presets": ["es2015", "react", "stage-2"], 
  "plugins": [["emotion", { "inline": true }], "universal-import"], 
  "env": { 
    "development": { 
      "plugins": ["react-hot-loader/babel"] 
    } 
  } 
} 
```

But when I switch to `babel-env`, `universal-import` fails to transpile the imports:
![screen shot 2017-10-10 at 18 22 13](https://user-images.githubusercontent.com/3305402/31398069-050fd1f4-ade8-11e7-98d9-b9230d7b32b0.png)

This is my current `.babelrc`:

```javascript
{
  "env": {
    "devClient": {
      "presets": [
        ["env", {
          "targets": { "browsers": ["android >= 4.4", "ios_saf > 9", "and_chr >= 56"] },
          "useBuiltIns": "usage"
        }],
        "react"
      ],
      "plugins": [["emotion", { "inline": true }], "universal-import", "react-hot-loader/babel"],
    },
    "devServer": {
      "presets": [
        ["env", {
          "targets": { "node": "current" }
        }],
        "react"
      ],
      "plugins": [["emotion", { "inline": true }], "universal-import"],
    }
  }
}
```

Any idea?

**Comment by faceyspacey** [comment]
When you use *super presets*, they do many things, which can break other plugins. In this case, they already do something for dynamic imports, and break our plugin:

https://github.com/babel/babel/blob/0189b387026c35472dccf45d14d58312d249f799/packages/babel-plugin-syntax-dynamic-import/src/index.js#L4

You don't need those plugins anymore when using webpack, as webpack automatically handles it. These older dynamic import plugins can cause problems. Unfortunately your best bet is to not use that package, or fork it and remove that line, or any other similar visitors they have for `import()`.

@swernerx encountered such an issue a while back and we worked on it. He may know more.

**Comment by faceyspacey** [comment]
also, I see you're using `emotion`--have you tried their `extractStatic` feature? Would love to see an article about using extracStatic and this setup's capability to split stylesheets.

I assume the reason you're not using it is because you still want dynamic styles. The future I'd like to see is a glamorous all-JS api with the ability to *both* generate static styles (and their sheets) AND dynamic styles. And what's more, the "static styles" would in fact be based on javascript evaluated at build time--so essentially they are only semi-static in that they can't take advantage of renderTime/runTime information, but they let you combine styles via standard javascript techniques like merging objects.

**Comment by luisherranz** [comment]
> When you use super presets, they do many things, which can break other plugins. In this case, they already do something for dynamic imports, and break our plugin:

The thing is... `babel-env` should not be using the `syntax-dynamic-import` plugin. That plugin is currently on [stage-2](https://babeljs.io/docs/plugins/preset-stage-2/) and babel-env shouldn't [include any stage-x plugin](https://github.com/babel/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest). Only es2017, es2016 and es2015 presets.

I'll investigate this further tomorrow. Maybe I can use the babel-env [exclude](https://github.com/babel/babel-preset-env#exclude) option to exclude `syntax-dynamic-import` (if it's really there) or switch to individual plugins until I find which one is breaking `universal-import`.

**Comment by luisherranz** [comment]
> also, I see you're using emotion--have you tried their extractStatic feature? Would love to see an article about using extracStatic and this setup's capability to split stylesheets.

Yes. I am migrating a project from `nextjs` and `styled-components` to `react-universal` and `emotion` :)

My first step is to use emotion in `inline` mode and once everything is working try the switch to `extractStatic` to see if there's an improvement in performance. As you can see in our `babel-env` conf, we are not worried about IE11, although I dislike having to use [css variables](https://github.com/emotion-js/emotion/blob/master/docs/extract-static.md) for dynamic styles, instead of javascript variables.

**Comment by luisherranz** [comment]
I took another look at this today.

Our `babel-preset-env` configuration (the one I pasted on the OP) is using these babel plugins:

```
Using plugins:
  check-es2015-constants {"android":"4.4","ios":"9.3"}
  transform-es2015-arrow-functions {"android":"4.4","ios":"9.3"}
  transform-es2015-block-scoped-functions {"android":"4.4","ios":"9.3"}
  transform-es2015-block-scoping {"android":"4.4","ios":"9.3"}
  transform-es2015-classes {"android":"4.4","ios":"9.3"}
  transform-es2015-computed-properties {"android":"4.4"}
  transform-es2015-destructuring {"android":"4.4","ios":"9.3"}
  transform-es2015-duplicate-keys {"android":"4.4"}
  transform-es2015-for-of {"android":"4.4","ios":"9.3"}
  transform-es2015-function-name {"android":"4.4","ios":"9.3"}
  transform-es2015-literals {"android":"4.4"}
  transform-es2015-object-super {"android":"4.4","ios":"9.3"}
  transform-es2015-parameters {"android":"4.4","ios":"9.3"}
  transform-es2015-shorthand-properties {"android":"4.4"}
  transform-es2015-spread {"android":"4.4","ios":"9.3"}
  transform-es2015-sticky-regex {"android":"4.4","ios":"9.3"}
  transform-es2015-template-literals {"android":"4.4"}
  transform-es2015-typeof-symbol {"android":"4.4"}
  transform-es2015-unicode-regex {"android":"4.4","ios":"9.3"}
  transform-regenerator {"android":"4.4","ios":"9.3"}
  transform-exponentiation-operator {"android":"4.4","ios":"9.3"}
  transform-async-to-generator {"android":"4.4","ios":"9.3"}
  syntax-trailing-function-commas {"android":"4.4","ios":"9.3"}
```

So there's no `syntax-dynamic-import` here. 

After that, I realized it doesn't conflict with `syntax-dynamic-import`. Instead, it *needs* it. So adding it back with the `stage-2` preset or the `syntax-dynamic-import` plugin did the trick.

```javascript
{
  "env": {
    "devClient": {
      "presets": [
        ["env", {
          "targets": { "browsers": ["android >= 4.4", "ios_saf > 9", "and_chr >= 56"] },
          "useBuiltIns": "usage"
        }],
        "react"
      ],
      "plugins": [["emotion", { "inline": true }], "syntax-dynamic-import", "universal-import", "react-hot-loader/babel"],
    }
  }
}
// or...
{
  "env": {
    "devClient": {
      "presets": [
        ["env", {
          "targets": { "browsers": ["android >= 4.4", "ios_saf > 9", "and_chr >= 56"] },
          "useBuiltIns": "usage"
        }],
        "react",
        "stage-2"
      ],
      "plugins": [["emotion", { "inline": true }], "universal-import", "react-hot-loader/babel"],
    }
  }
}
```

**Comment by luisherranz** [comment]
Maybe this should be mentioned in the README?

**Comment by faceyspacey** [comment]
the thing is it doesn't need it:

https://github.com/faceyspacey/universal-demo/blob/master/.babelrc#L3

Webpack 3 will automatically handle it. I think your setup may have undone it somehow. I really don't know. 

At some point, I'm gonna do a PR to webpack that removes the need for as much of this stuff as possible. I have some ideas.

**Comment by luisherranz** [comment]
`syntax-dynamic-import` is part of `stage-2`:
https://babeljs.io/docs/plugins/preset-stage-2/

I've cloned the `universal-demo` repo and if you remove the `stage-2` preset from your `.babelrc`, the same problem appears:
![screen shot 2017-10-19 at 10 09 46](https://user-images.githubusercontent.com/3305402/31760661-b5bc0b02-b4b5-11e7-9259-221daade0ac5.png)

I've double checked the webpack version in my cloned `universal-demo` and it is 3.7.1.

Maybe `stage-2` was always there when you were developing this?

**Comment by faceyspacey** [comment]
it was. but you can't really develop these modern babel-based apps without at least stage 2.
