### ISSUE TITLE
Dynamic imports not working with additional path after the dynamic part

### ISSUE THREAD

**Issue by luisherranz** [faceyspacey/babel-plugin-universal-import#19]
I'm trying to create a package system using `universal-import` but when the dynamic part is not the last one, it fails.

This is the `UniversalComponent`:
```javascript
const UniversalComponent = universal(
  props => import(`../../packages/${props.page}/src/pwa/index.js`)
)
```
The chunks create by Webpack have this structure:
![screen shot 2017-10-18 at 16 16 55](https://user-images.githubusercontent.com/3305402/31723879-59e38ed0-b420-11e7-999a-9f23580a0fa4.png)

This means the names of the chunks are `packages/${props.page}-src-pwa-index.js`.

But `webpack-flush-chunks` is trying to find `packages/${props.page}/src/pwa/index.js` and the SSR fails.

```
[FLUSH CHUNKS]: Unable to find packages/connection/src/pwa/index.js in Webpack chunks. Please check usage of Babel plugin.
PATH /connection
DYNAMIC CHUNK NAMES RENDERED [ 'packages/connection/src/pwa/index.js' ]
SCRIPTS SERVED [ 'bootstrap.js', 'main.js' ]
STYLESHEETS SERVED [ 'main.css' ]
```

It works fine if the dynamic part is the last part, like in your examples:
```javascript
const UniversalComponent = universal(
  props => import(`../../packages/${props.page}`)
)
```
or if it's not dynamic:
```javascript
const UniversalComponent = universal(
  () => import('../../packages/general/src/pwa/index.js')
)
```
In the last case, the chunks created by Webpack don't contain hyphens and `packages/connection/src/pwa/index.js` is the proper chunk name:
![screen shot 2017-10-18 at 16 18 41](https://user-images.githubusercontent.com/3305402/31724075-f81dea64-b420-11e7-8ee3-a3fbcc86e3c8.png)

What do you think? Is it easy to fix?

**Comment by faceyspacey** [comment]
I likely won't be able to get to it, but perhaps the context-replacement-plugin will let you rewrite things:

https://webpack.js.org/plugins/context-replacement-plugin/

If you do wanna do a PR, it's around here:
https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L61

and I'm not 100% sure right now, but we should be able to replace slashes with hyphens in this var: `quasis[1]`.


However, if u just want this done, likely the following will work in userland:

```js
chunkNames.map(name => name.replace('-src-pwa-index.js', '/src/pwa/index.js'))
```

Then pass that to `flushChunks` and it will be able to lookup the correct chunk name.

**Comment by luisherranz** [comment]
I'll try those solutions and I'll let you know. Thanks James!

**Comment by luisherranz** [comment]
This seems to work great in both cases (`./pages/${props.page}` and `./pages/${props.page}/other/path`):
```javascript
// At the beginning of the file:
function prepareChunkNamePath(path) {
  return path.replace(/\//g, '-')
}

// ...

// The new createTrimmedChunkName function:
function createTrimmedChunkName(importArgNode) {
  if (importArgNode.quasis) {
    const quasis = importArgNode.quasis.slice(0)
    const baseDir = trimChunkNameBaseDir(quasis[0].value.cooked)
    quasis[0] = Object.assign({}, quasis[0], {
      value: { raw: baseDir, cooked: baseDir }
    })

    // <<<< Added this
    if (quasis[1]) {
      const newPath = prepareChunkNamePath(quasis[1].value.cooked)
      quasis[1] = Object.assign({}, quasis[1], {
        value: { raw: newPath, cooked: newPath }
       })
    }
    // >>>>

    return Object.assign({}, importArgNode, {
      quasis
    })
  }
  const moduleName = trimChunkNameBaseDir(importArgNode.value)
  return t.stringLiteral(moduleName)
}
```

I've forked the repo and added a new snapshot:
```javascript
'dynamic import (string template with nested folder)': 'import(`./base/${page}/nested/folder`)'
```

The output is:
```javascript
import(\`./base/\${page}/nested/folder\`)

      ↓ ↓ ↓ ↓ ↓ ↓

import _path from \\"path\\";
import _importCss from \\"babel-plugin-universal-import/importCss.js\\";
import _universalImport from \\"babel-plugin-universal-import/universalImport.js\\";
_universalImport({
  id: \\"./base/\${page}/nested/folder\\",
  file: \\"currentFile.js\\",
  load: () => Promise.all([import( /* webpackChunkName: 'base/[request]' */\`./base/\${page}/nested/folder\`), _importCss(\`base/\${page}-nested-folder\`)]).then(proms => proms[0]),
  path: () => _path.join(__dirname, \`./base/\${page}/nested/folder\`),
  resolve: () => require.resolveWeak(\`./base/\${page}/nested/folder\`),
  chunkName: () => \`base/\${page}-nested-folder\`
});
```

The other snapshots don't change so I guess everything is ok.

The only thing I'm not sure of, is the `importCss` part:
```javsacript
_importCss(\`base/\${page}-nested-folder\`)
```
but I've tested it in my app and CSS is working great. Now `window.__CSS_CHUNKS__` use the proper chunkNames. For example:
```javascript
window.__CSS_CHUNKS__ = {
  'packages/saturn-app-theme-worona-src-pwa':
    '/static/packages/saturn-app-theme-worona-src-pwa.css',
  'packages/general-app-extension-worona-src-pwa':
    '/static/packages/general-app-extension-worona-src-pwa.css',
};
```

So I guess is ok.

I've done a PR: https://github.com/faceyspacey/babel-plugin-universal-import/pull/20

We can keep talking there :)
