### ISSUE TITLE
Feature Request: Allow for disabling CSS Part on a import() level

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/babel-plugin-universal-import#2]
I currently use import() in my application for both view-related files (RFR-connected) and things like polyfills and message files. Currently the babel plugin transpiles all import() in the same way and adds a `importCSS` to the chain which results in a warning because there is no such file.

I just thought about whether we can make this better controllable e.g. by also using some kind of command dialect e.g. like the magic comments by webpack or plain a simple using a different kind of method call e.g. instead of `import()` just use `importWithCSS()`.

**Comment by faceyspacey** [comment]
Or just not warn lol.

I'm trying to preserve the original API in order to be as frictionless as possible and become popular.

Some idea will come to achieve the best of all worlds.

**Comment by faceyspacey** [comment]
closing this. will be turned off with debug: false in the future.
