### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by suciuvlad** [faceyspacey/babel-plugin-universal-import#22]
Doesn't work with Babel 7:

```
  function getUniversalImport(p) {
    if (!p.hub.file[universalImportId]) {
      const universal = p.hub.file.addImport(
        'babel-plugin-universal-import/universalImport.js',
        'default',
        'universalImport'
      )
      p.hub.file[universalImportId] = universal
    }

    return p.hub.file[universalImportId]
  }
```

> Error: This API has been removed. If you're looking for this functionality in Babel 7, you should import the 'babel-helper-module-imports' module and use the functions exposed  from that module, such as 'addNamed' or 'addDefault'.

**Comment by faceyspacey** [comment]
I've been waiting a little bit before upgrading to babel 7. It's probably a good time now. PRs welcome.

**Comment by faceyspacey** [comment]
this has been addressed thanks to @hulkish
