### ISSUE TITLE
Disable CSS warning

### ISSUE THREAD

**Issue by okcoker** [faceyspacey/babel-plugin-universal-import#23]
I'm not using css in any of my components right now. And when I get there, I was thinking of using styled-components anyway. Is there a way to disable the no-chunk-found warning?

`importCss.js:16 [UNIVERSAL-IMPORT] no chunk, chunkName , found in "window.__CSS_CHUNKS__".`

I included the `flushedChunks.cssHash` in my server render thinking it would suppress the first warning about the global not being found but now it just complains about specific chunks not being found.

I feel this option should be not even include the `import importCss` stuff in the compiled output. I can send a PR if this is not possible yet.

**Comment by faceyspacey** [comment]
monkeyPatch console.warn for now to detect that message and do nothing. im gonna add a `debug` mode in the future that turns off all warnings in all these packages.

**Comment by okcoker** [comment]
But also besides the warnings, there is no point of having the imported css file and promise if I'm not doing anything with CSS right? Do you think it's worth it to have that part be optional?

**Comment by faceyspacey** [comment]
it short-circuits early so it's not a perf problem:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/importCss.js#L7

I do think it's worth being optional, but i want to revisit it holistically as part of the next big update. For now, it's just these console warnings, which isn't really a real issue.

**Comment by okcoker** [comment]
Works for me 👍

**Comment by faceyspacey** [comment]
actually, if u wanna do a PR to provide a babel plugin option called `disableWarnings` go for it. I've been too protective that I didn't want to change much until I could invest the time, but I know this one will be fine, and many people have been bothered by it. You'd have to pass the option to `importCss()` through this template:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L130

You can get the option's value similar to as is done here:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L187

No pressure.

**Comment by faceyspacey** [comment]
so a second parameter, a boolean, `disableWarnings`, would be passed here:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/importCss.js#L5
