### ISSUE TITLE
Fetches css resource twice + gzip problem

### ISSUE THREAD

**Issue by baldurh** [faceyspacey/babel-plugin-universal-import#26]
There are two closely related issues.

First, because of the `link.href` + `img.src` hack to load the chunk there are two requests made at the same time so the second one won’t utilize the browser cache.
Second, the `img.src` hack downloads an uncompressed version of the resource as can be seen in this screenshot:
![image 2017-11-29 at 1 53 57 e h](https://user-images.githubusercontent.com/1823617/33379209-6a16b61e-d50f-11e7-838a-eb672daa0f8c.png)

First we download the compressed css file via `link.href` but then we download it again uncompressed via `img.src`.

Now, the first issue can be resolved by moving `link.href` inside the `img.onerror` handler. That way we download the uncompressed version first and the second request is resolved from cache. That still leaves the second issue though.

**Comment by faceyspacey** [comment]
Excellent idea. I'm closing this out. Please submit a PR.

As for not being compressed, maybe it's just the devtools saying that. There's only one version being sent from the server.

Another option FYI is to do this only in the browsers that need it. You could even combine approaches.
