### ISSUE TITLE
Can you make it more clear how to use this?

### ISSUE THREAD

**Issue by sontek** [faceyspacey/babel-plugin-universal-import#28]
Hey, I'm having an issue where I'm using `extract-text-webpack-plugin` with codesplitting (currently react-loadable):

```
const LoadableFeatures = Loadable({
    loader: () => import('../components/features'),
    loading: Loading,
});
```

and this is using `syntax-dynamic-import`.    I'm trying to figure out what combination of things I need to do to use your libraries since they seem to be solving the thing I want.

Do I need `react-universal-component` or just `babel-plugin-universal-import`?   How do I dynamically load a component that has its own CSS and have that CSS chunked?

I've tried just using `react-universal-component` by itself:

```
const LoadablePricing = universal(() => import('../components/pricing'));
```

and the CSS doesn't get extracted to its own chunk.

**Comment by faceyspacey** [comment]
You need to use all of the above. Not Loadable. 

Study the react-universal-component + webpack-flush-chunks (primarily the latter) to get it all. Then babel-plugin-universal-component and extract-css-chunks-webpack-plugin will make more sense. Basically all 4 are to be used together.

**Comment by sontek** [comment]
Ok, so if I understand...

- Replace extract-text-webpack-plugin with extract-css-chunks-webpack-plugin
- Add babel-plugin-universal-import (Does this replace `syntax-dynamic-import` or in addition to?)
- Replace react-loadable with  `react-universal-component`

I wasn't clear with what the use case was for `webpack-flush-chunks`, I don't do SSR (our backend is python, not javascript).  Do I still need it?

**Comment by faceyspacey** [comment]
For the second point you usually don't have to have them both, but if it's not working try adding the additional plugin.

Since you aren't doing SSR there is another plugin by one of our users mentioned on the extract-css-chunks readme for SPAs that you need instead so dual import of both js plus CSS works.

**Comment by sontek** [comment]
ok... so this is almost working.

- `css-chunks-html-webpack-plugin` is injecting the CSS files into my `index.html`

```
window.__CSS_CHUNKS__ = {"containers/learn_container": ... etc
```

- `extract-css-chunks-webpack-plugin` is extracting them to their own bundles

```
 dist/css/|grep -v .gz|grep -v .map
app.3eeab27cb082ac4a6d995f1650c3c3f3.css
components
containers
design_patterns.d798f5725576fb5de8bcf5869c4464f4.css
forms.2cb9b80bc2f8de0082c276666755f97b.css
layout.15b6e4710135b445a5ac32cd60d4fc4e.css
site.96d6e7fd064029fe759ad4599df91022.css
```

but I'm not getting the file `dist/css/components/pricing.7aee38290ce8cecb2f21a442a4c63bb3.css` loaded when I load this component:

```
const LoadablePricing = universal(() => import('../components/pricing'));
```

what part did I screw up that would cause that last piece to not work?

**Comment by sontek** [comment]
Ok, I see whats happening.   Two issues:

1. This async fetches the CSS if the page isn't the first page load. But it doesn't load the asset if its the first page. So you have to visit a different page and then go back to see the styles.

2. It isn't running it through `postcss-loader` so the asset isn't completely processed.

Do you know how I could fix those two things?

**Comment by sontek** [comment]
The sass thing was my fault, I'm down to just #1.  The CSS from the async components aren't loaded on the initial requested, they are loaded after if they aren't on the initial request.
