### ISSUE TITLE
babel-plugin-universal-import unresolvable from a nested package's babel config

### ISSUE THREAD

**Issue by franjohn21** [faceyspacey/babel-plugin-universal-import#29]
At NerdWallet we use a centralize build repo to share build settings across many apps/teams. Here is an example of the folder structure within a given app:

```
node_modules
  -@nerdwallet/build-tool
      -babelrc.js
      -webpack.config.js
      -node_modules
         -babel-plugin-universal-import
- app.js
- webpack.config.js // inherits from @nerdwallet/build-tool
```

Within our build-tool's babel config we require this plugin via 
`require.resolve('babel-plugin-unversal-import')`. This works fine for babel plugins in general, however this plugin in particular injects an import to a hard coded path `babel-plugin-unversal-import/importCss` and `babel-plugin-unversal-import/universalImport`.

Because the webpack context is running from the top level, **this breaks module resolution** (and I have not been able to work around it with an alias).

Is it possible we can [set the source](https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L9) via a `require.resolve('./importCss')` and `require.resolve('./universalImport')` such that these always resolve correctly relative to where the babel plugin is?

Happy to make a PR if this is the correct solution.

---

_For SEO this is the error message printed:_
`Module not found: Error: Can't resolve 'babel-plugin-universal-import/importCss'`
`Module not found: Error: Can't resolve 'babel-plugin-universal-import/universalImport'`

**Comment by faceyspacey** [comment]
Not sure if we want to tie to webpack like that.

I don't get how it wouldn't work since the path to the plugin is its relative node_modules path. There must be a common solution for this.

**Comment by ScriptedAlchemy** [comment]
I’ve got a similar setup where I have my own node module with all webpack configuration. I’ve found that npm linking it back to my project breaks the compile because it tries and resolves from the origin file. Not sure if it’s related but off the bat it does sound similar. I’m planning to investigate further and see where the issue is. If it fixes my scenario, it might work for you as well, assuming you have not already moved on to another workaround 😂

**Comment by ScriptedAlchemy** [comment]
Webpack 4 updates on the way, should resolve this @franjohn21

**Comment by ScriptedAlchemy** [comment]
Actually this might be a wider issue. I am experiencing this across the board when running webpack in non-standard ways. If you use require.resolve, don't do that, just use require. Thats what causes this
