### ISSUE TITLE
Feature Request: Loading additional data files / messages together with JS/CSS

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/babel-plugin-universal-import#3]
The Babel plugin currently transpiles a plain JS import into a `Promise.all` with multiple imports which are all returning Promises. I have a use case which has an additional but comparable need. In our application we have route-specific message files which are used for translating messages. There is one message file for each language for each route.

- preferences/Preferences.js
- preferences/Preferences.css
- preferences/messages/de.json
- preferences/messages/en.json
- preferences/messages/fr.json

Ideally it would be possible to load these things together with the JS and CSS in parallel but depending on the users locale.

Language detection and file loading can be implemented using a helper method like `importCSS("chunkName")` e.g. `importMessages("chunkName")`.

Only outstanding issue here might be how `importMessages` receives the information about the current locale. Probably one have to inject this info into the HTML page like we do for `CSS_CHUNKS` right now.

There is one difference to CSS though: Message files have to be loaded dynamically on the server too, otherwise server side rendering with differ from client side rendering.

**Comment by swernerx** [comment]
It might be actually better implemented in or with the help of https://github.com/faceyspacey/react-universal-component as often times you HOC the original component with the resulting messages e.g. via `IntlProvider` from [react-intl](https://github.com/yahoo/react-intl)

**Comment by faceyspacey** [comment]
Server rendering around this is very complicated. It involves recursively resolving on the server and rehydrating on the client.

That said u stumbled on a clue of what is to come. I built it a month ago. I just gotta refine it.

**Comment by swernerx** [comment]
Okay sounds good. Tell me when you need some beta tester for this. :)
