### ISSUE TITLE
async loaded stylesheets not editable in Chrome

### ISSUE THREAD

**Issue by hurrtz** [faceyspacey/babel-plugin-universal-import#30]
Hey guys,

I am not really sure where to put this, but before I file an issue for Chromium I wanted to check with you first:

When a stylesheets gets injected async into my html then the styles get applied but are not editable in the Chrome dev tools. Whenever I change the link element that contains the stylesheet, thus enforcing Chrome to reload the resource, the styles become editable.

After a stylesheet got injected (greyed out areas in inspector are not editable)
![screen shot 2017-12-08 at 06 56 12](https://user-images.githubusercontent.com/1146645/33752978-3d394c24-dbe5-11e7-92d6-7537521fad69.png)

After Chrome has reloaded the stylesheet
![screen shot 2017-12-08 at 06 56 48](https://user-images.githubusercontent.com/1146645/33752979-3d567ce0-dbe5-11e7-8270-174f02d007a0.png)

Is this at all something that belongs to this babel module?

**Comment by ScriptedAlchemy** [comment]
Will be addressed in the next update
