### ISSUE TITLE
Is there a recommended usage for hard-source-webpack-plugin when using universal-import?

### ISSUE THREAD

**Issue by furkle** [faceyspacey/babel-plugin-universal-import#32]
I have my entire SSR/code-splitting TSX project going smoothly, and I saw I could reduce my build times somewhat by using `hard-source-webpack-plugin`. This works fine the first time, and everything looks fine, but the second time, I get a warning for any given page I try to load:

`[FLUSH CHUNKS]: Unable to find Pages/ReadWrite in Webpack chunks. Please check usage of Babel plugin.`

and none of my CSS is rendered into the page. Is there a solution or recommendation for this, or should I try to ask the hard-source team, or should I just stop microoptimizing?

**Comment by faceyspacey** [comment]
the last one unfortunately :( 

i haven't heard of anyone able to get that package to work. there's an issue already open in one of these packages generally related to such additional webpack plugins, so im gonna close this.

#neverStopMicroOptimizing
#whoCaresWhatPeopleSay

but i'd tap out on this one.

**Comment by furkle** [comment]
Thanks so much! I'll post in here again if I ever happen to get it working.
