### ISSUE TITLE
Resolving import on the server side

### ISSUE THREAD

**Issue by Arturszott** [faceyspacey/babel-plugin-universal-import#33]
On the server side while trying to resolve the dynamic import I receive error message that `load is not a function`. 

It's probably because transpiled object is `thennable`.

My code example: `Promise.resolve(import('./components/pages/SomePageITryToImport'))`.

What's the recommended solution? Right now I have to check if i am on the server to avoid resolving. Is there any way to configure `makeThennable`?

**Comment by emphaticsunshine** [comment]
Any update on this?

**Comment by faceyspacey** [comment]
`import('./components/pages/SomePageITryToImport').then` should work.

**Comment by Arturszott** [comment]
`then` works by itself, but then it throws error on the server side.

**Comment by zackkirsh** [comment]
@Arturszott does the open PR solve your problem?

**Comment by Arturszott** [comment]
I managed to somehow avoid this problem. It's not relevant anymore.
