### ISSUE TITLE
magic comments not working for non-universal-component imports

### ISSUE THREAD

**Issue by rileylnapier** [faceyspacey/babel-plugin-universal-import#34]
hey @faceyspacey, so in my build, i'm doing a couple of dynamic imports of redux files

```js
import(/* webpackChunkName: 'chunks/[request]' */ `./redux/es/page-types/${pageType}/index.js`)
```

and other places using universal-component.

the problem that i see is that `babel-universal-import` seems to be wiping out my `webpackChunkName` :(

if i remove the babel plugin, my chunks get named correct.

what can/should i do to fix this?  thanks

**Comment by rileylnapier** [comment]
is that what this is?  https://github.com/faceyspacey/babel-plugin-universal-import/pull/13

seems to be stale?

**Comment by faceyspacey** [comment]
you can't use `webpackChunkName` with this. Yes, that's what that PR is about. It needs to be finished.

**Comment by zackkirsh** [comment]
@rileylnapier ive got an open PR which will enable this, check the PR on this repo
@faceyspacey worth closing this out?

**Comment by ScriptedAlchemy** [comment]
This has been resolved via an update
