### ISSUE TITLE
Server side rendering not happening

### ISSUE THREAD

**Issue by emphaticsunshine** [faceyspacey/babel-plugin-universal-import#35]
I am trying to get a component server side rendered. Two things noticed while debugging:

- `require.async` comes as true on server
- It doesn't find it inside` installedModules`

Any idea, what it might be?

**Comment by faceyspacey** [comment]
Actually I have no idea what that issue is. I'd reduce your setup to the simplest case similar to the boilerplate, get that working, and then proceed.
