### ISSUE TITLE
client and server did not match in Typescript or non-Babel environments

### ISSUE THREAD

**Issue by cixiu** [faceyspacey/babel-plugin-universal-import#36]
I follow Typescript and non-Babel environments demo to configure UniversalComponent:
```javascript
import universal from 'react-universal-component'
import * as path from 'path'
import universalImport from 'babel-plugin-universal-import/universalImport'
import importCss from 'babel-plugin-universal-import/importCss'
import { IStoreState } from '../../store/types'

declare const require: any

const UniversalComponent = universal((props: any) => universalImport({
  chunkName: () => props.page,
  path: () => path.join(__dirname, `../../page/${props.page}/${props.page}`),
  resolve: () => require.resolveWeak(`../../page/${props.page}/${props.page}`),
  load: () => Promise.all([
    import( /* webpackChunkName: '[request]' */ `../../page/${props.page}/${props.page}`),
    importCss(props.page)
  ]).then(proms => {
    return proms[0]
  })
}), {
  minDelay: 500
})
```
When i start server, i get both warning ```[FLUSH CHUNKS]: Unable to find Home in Webpack chunks. Please check usage of Babel plugin``` in server side and  ```Warning: Text content did not match. Server: "Home+10" Client: "Loading..." ```in client browser。

so how #to solve this problem?
or what I may have done incorrectly?
thanks in advance

**Comment by ScriptedAlchemy** [comment]
Try it now. Might be the bug I patched in version 2

**Comment by cixiu** [comment]
@zackljackson Yes, I have solved this problem by changing chunkname to `${props.page}-${props.page}`.But  built filename liking `Home-Home.js` have a little ugly。there is any methods to change this?

**Comment by ScriptedAlchemy** [comment]
@cixiu is this still a issue? About to release webpack 4 upgrades. 

Try using a normal webpack chunk name, not request. It might help resolve this. Nesting chunks are hard to solve due to webpack changes

**Comment by ScriptedAlchemy** [comment]
Your issue is because of your file name

You should just make Home, index.js then you can import Home and it'll just get the index. Ultimately this is a issue with webpack chunkname conventions if im not mistaken
