### ISSUE TITLE
Add support for multiple webpack magic comments and Prefetch/Preload

### ISSUE THREAD

**Issue by madiodio** [faceyspacey/babel-plugin-universal-import#59]
First, let me thank you for this awesome tool (alongside `react-universal-component` and `webpack-flush-chunks`)

I've noticed that #43 was aimed at supporting webpack magic comments which enable thinks like custom chunkNames and lazy mode. And recently, it has been introduced 2 new comments `webpackPrefetch` and `webpackPreload` ([webpack 4.6.0](https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c)) that allow you to instruct webpack to use `<link rel=”prefetch/preload”>` so you can do this as a loading strategy:

```js
universal(() => import(/* webpackChunkName: "route--home", webpackPrefetch: true */"./home"))
```

but unfortenately the second comment doesn't work and break the chunkName which results in `route--home, webpackPrefetch: true.js`. So is there currently any plan to add support these handy features?

Thanks.

**Comment by faceyspacey** [comment]
I think we definitely want that. Just gotta find the time.

**Comment by madiodio** [comment]
Thanks for the prompt reaction.

**Comment by ramakay** [comment]
@faceyspacey  - is there a specific area in the library where this would need to be added, I can attempt a PR

**Comment by ScriptedAlchemy** [comment]
This is something I would like to add, the best thing would be to look at the `Import` visited section at the bottom of the file, I have a function that checks if magic comments exist, it might just need to be updated slightly

**Comment by ScriptedAlchemy** [comment]
This has been added. Install latest and check docs

**Comment by ntucker** [comment]
@ScriptedAlchemy where are the docs? https://webpack.js.org/guides/code-splitting/ has 0 examples of more than one comment
