### ISSUE TITLE
Make universal component optional

### ISSUE THREAD

**Issue by isidrok** [faceyspacey/babel-plugin-universal-import#62]
Hi, I'm using this plugin in conjunction with `extract-css-chunks-webpack-plugin` in order to lazy load css but since I'm not using `react-universal-component` babel outputs the following warning:

```bash
WARNING in ./node_modules/babel-plugin-universal-import/universalImport.js
Module not found: Error: Can't resolve 'react-universal-component' in ...
```
Would it be possible to disable this warining via an option or something?

Thanks.

**Comment by ScriptedAlchemy** [comment]
Go into your node modules, and check the package.json version for me

**Comment by isidrok** [comment]
I'm using version `3.0.0`.

**Comment by ScriptedAlchemy** [comment]
Try bumping it to its latest, make sure you’ve got no lock files. Otherwise, if you have a repo I can better assist

**Comment by isidrok** [comment]
I highly suspect that the code causing the warning is [this one](https://github.com/faceyspacey/babel-plugin-universal-import/blob/webpack-4/universalImport.js#L30), will try to confirm it during this week.

**Comment by ScriptedAlchemy** [comment]
If you can open a PR to solve your issue, assuming there's a problem with our code, please feel free to do so. Also let me know the findings and ill try to find time

**Comment by isidrok** [comment]
I can confirm the warning is triggered by using `require.resolveWeak('react-universal-component')`. Will look at how to pass options to babel plugins in order to make the `setHasPlugin()` optional in case some users are not using `react-universal-component` but just the plugin.
I'll probably have time for the PR this week.

**Comment by isidrok** [comment]
I've had a look at the code and I can't find a clear way to separate the `dual import` behavior from the `react-universal-import` one. Since I'm only using this plugin in conjunction with `extract-css-chunks-webpack-plugin` to lazy load css but I'm not doing any SSR (Which I think is the purpose of this tool) I'll switch to another option for just lazy-loading css.

Will mark this as closed, thank you for your time!
