### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by volkanunsal** [faceyspacey/babel-plugin-universal-import#68]
Upgraded to webpack 4.18.0 and started getting these warnings

```
WARNING in ./node_modules/babel-plugin-universal-import/universalImport.js 33:18-37
Critical dependency: the request of a dependency is an expression
```

**Comment by ScriptedAlchemy** [comment]
Make sure you have the latest. This was fixed I believe

**Comment by volkanunsal** [comment]
@ScriptedAlchemy This is the latest release they have from a day ago. Maybe the fix hasn't been merged into the release yet.

**Comment by ScriptedAlchemy** [comment]
I highly doubt it exists. Clear your yarn or package lock files. Delete node modules and do a clean install. I’ve been tracking the issue across multiple projects. 

There is however a warning in react universal component. Which I am patching. But the Babel plugin no longer has this problem

**Comment by volkanunsal** [comment]
Upgrading this package fixes it. Thanks.
