### ISSUE TITLE
Getting path not found with "node: false"

### ISSUE THREAD

**Issue by jooj123** [faceyspacey/babel-plugin-universal-import#72]
I am getting the error: `Cannot find module "path"` when using `babel-plugin-universal-import`
(similar to issue:
https://github.com/faceyspacey/babel-plugin-universal-import/issues/4 )

(im using version `2.0.2`)

I have client config `node: false` https://webpack.js.org/configuration/node/#node to prevent node code from ending up in the bundle (and fail fast instead of adding bloated polyfills)

Can this babel plugin be used without node code being placed into the client bundle ?

**Comment by ScriptedAlchemy** [comment]
Hmmm I’ll have to check this out tonight. 

If you check the demo project. You will notice some things we exclude from externals. As long as those are bundeled in - I think it should work. I’ll need to check this myself though. If you want, clone down the repo and do some debugging, I might help us achieve a resolution faster

**Comment by jooj123** [comment]
@ScriptedAlchemy are you talking about this ? https://github.com/faceyspacey/universal-demo/blob/3c72bcaccf6618ce7eefc63dc7035b46164d11e3/webpack/server.dev.js#L16

**Comment by lutzk** [comment]
@jooj123 in case it helps:
i fixed it with setting all explicitly to false:
```
node = {
  Buffer: false,
  __dirname: false,
  __filename: false,
  console: false,
  global: false,
  process: false,
  ...
}
```
but path might be needed to work for the plugin

update:
`path: 'empty',` works

error comes from `path: () => path.join(__dirname, './Foo.js'),`
but it seems jut used on server
