### ISSUE TITLE
HMR is broken with non-universal import()

### ISSUE THREAD

**Issue by cdoublev** [faceyspacey/babel-plugin-universal-import#78]
Hello there,

I'm not 100% sure that my issue is related to the babel plugin or RUC.

I created the following repository (React SSR app) to demonstrate the issue when executing an import() which is not handled by RUC (ie. as an universal component), that is breaking HMR. I use this import to polyfill the client if required.

**Steps to reproduce the issue**

1. git clone https://github.com/cdoublev/react-ssr-debug-hmr
2. `npm start` and open your browser
3. Open src/universal/hello.js in your editor and change the text: no hot update
4. Open src/index.js in your editor and remove/comment L#5
5. Change the text of src/universal/hello.js again: hot update

I spend about 3 hours on this issue but I didn't look at the sources of this plugin, and it's been a long time since I read the posts from faceyspacey, explaining what it does and how chunks ids are saved and shared between server and client.

I will try to look deeper soon, but as I can easily remove this import() in dev mode, I will first continue the work I was on. But any advice/comments would be appreciated.

**Comment by ScriptedAlchemy** [comment]
@theKashey is this what you were DMing me about?

**Comment by ScriptedAlchemy** [comment]
this is likely due to some new changes in React or RHL. I was just informed of this today by another author who maintains RHL. Ill speak with him and see if he will lend a hand on RUC or tell me what i need to patch

**Comment by theKashey** [comment]
Universal is not compatible with webpack HMR. To make it _compatible_ universal has to:
- call `import` in the constructor (Dan said that's ok, react-loadable is doing it )
- or somehow detect `forceUpdate` from RHL (bad idea)
- or use hooks somewhere, and RHL will reset hook (imported-component is doing it)

In short - something has to to-import chunk. Probable the `.1` is only possible for RUC for now.

**Comment by cdoublev** [comment]
In case it might be valuable: moving the import of the module (src/polyfill.js) which executes the dynamic import(), from a module (index.js) which is not executed server side, to a SSRed module (app.js), fixes HMR.

I'm not sure I fully understand the meaning of "calling import in the constructor" (of RUC? Isn't it already doing it?), but if you think I should close this issue and open a new one in the RUC repo, please tell me.

Thank you for the quick answer @ScriptedAlchemy, I know you're pretty busy since multiple months. Please note that it's not a high priority issue (for me, at least). :)

**Comment by theKashey** [comment]
Not it does not - https://github.com/faceyspacey/react-universal-component/blob/master/src/index.js#L241-L245
```js
    constructor(props: Props, context: {}) {
      super(props, context)
      this.state = this.init(this.props, this.context)
      // $FlowFixMe
      this.state.error = null
    }
```
While calling `UniversalComponent.preload()` would be probably enought to fix the problem.

Could you inject this one-line change into your version on RUC(directly in the node_modules) to verify that it would be enought.
If it will - let's move to RUC repo then to fix the root cause.

**Comment by ScriptedAlchemy** [comment]
@theKashey 
![image](https://media0.giphy.com/media/qPVzemjFi150Q/giphy.gif?cid=790b7611b74361ce2b8968c439c4c8dc34124aa8c67d092d&rid=giphy.gif)

**Comment by cdoublev** [comment]
I disabled Webpack HashedModuleIds plugin.

**Error output**

```
Error: Cannot find module './undefined'
  at Function.webpackContextResolve [as resolve] (webpack:///./src/universal_weak_^\.\/.*$?:20:11)
  at resolve (webpack:///./src/universal/app.js?:35:103)
```

./src/universal/app.js

```js
  const loadingFn = ({ page }) => 
    // ...
    /* L35 */ resolve: () => /*require.resolve*/(__webpack_require__("./src/universal weak recursive ^\\.\\/.*$").resolve(`./${page}`)),
    // ...
})

**Comment by cdoublev** [comment]
`Error: Cannot find module './undefined'` reported in previous comment came from the module imported on top of hot + universal, which was returning `await import()` on client but `undefined` on server:

```js
  // before
  export default async () => {
    if ('undefined' === typeof window) {
        return
    }
    return await import('./async')
}
```
I [simplified](https://github.com/cdoublev/react-ssr-debug-hmr/commit/3004c06ad8787fa33a792cdb229b154e0b58e965) the reproduction repository and this module is now imported both on client and server:

```js
  // after
  export default async () => await import('./async')
```

Here is a simplified recap to demonstrate what I mean by ***HMR fail with import() on top of (hot+)universal***:

```js
  // client.js
  // Those two lines prevents HMR of ./async/hello.js
  import polyfill from './polyfill'
  polyfill().then(require => require())

  hydrate(<App />, document.getElementById('app'))

  // ./polyfill.js
  export default async () => await import('./fix-browser') // Shouldn't be recorded

  // ./fix-browser.js
  export default console.log('client fixed!')

  // ./app.js
  // Import and execute polyfill here to fix HMR
  export default hot(universal(import('./async/hello'))) // Should be recorded

  // ./async/hello.js
  export default () => <h2>Helloooo</h2>
```

When RUC is executed on top of the polyfill module, it works, but now the latter is executed when rendering server side.

If I'm still wrong, I'd rather let you handle this issue but I'll watch for updates to try to understand what was going on.

**Comment by ScriptedAlchemy** [comment]
Import on its own needs the then() callback. Even if it’s not used, that’s what fires off the module. Otherwise dynamic imports are transformed by Babel plugin but never called upon like they are in the HOC,

**Comment by cdoublev** [comment]
> Otherwise dynamic imports are transformed by Babel plugin but never called upon like they are in the HOC,

Yep, and I don't know how this module (executing a dynamic import) could prevent an hot update in this HOC (RUC). If you remove the HashedModuleIdPlugin, you'll see the following warning when doing an update to `./src/async/hello`:

```
Ignored an update to unaccepted module ./src/async/hello.js 
  -> ./node_modules/react-universal-component/dist/requireById/index.js 
  -> ./node_modules/react-universal-component/dist/utils.js 
  -> ./node_modules/react-universal-component/dist/index.js 
  -> ./node_modules/babel-plugin-universal-import/universalImport.js 
  -> ./src/polyfill.js 
  -> ./src/index.js 
  -> 0

[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/async/hello.js
```

**Comment by cdoublev** [comment]
Hello to both of you,

I (force) pushed an even simpler version of the [demo repo](https://github.com/cdoublev/react-ssr-debug-hmr/) with the latest versions of its dependencies.

`git clone https://github.com/cdoublev/react-ssr-debug-hmr`

**Steps to reproduce the issue**

1. npm start and open your browser (localhost:8080)
2. Open src/universal/hello.js in your editor and change the text: no hot update

**Steps to "fix" the issue (and demonstrate the responsibility of this plugin)**

1. Remove `(babel-plugin-)universal-import` from the babel plugins prop in `babel.config.js`
2. npm start and open (or refresh) your browser (localhost:8080)
3. Open src/universal/hello.js in your editor and change the text: hot update

As suggested in my previous comment, importing the async module only client side breaks HMR.

I took a look at the source code of this plugin but unfortunately, my Chrome debugger won't start and my knowledge of Babel plugins ` === null`.

For the sake of answering you (I'm really sorry to forget it), @theKashey, since you asked me to add `UniversalComponent.preload()` in `UniversalComponent`'s constructor: before simplifying the demo repo, it was throwing an error but now it just has no effect (HMR stays broken). And for me, `this.init(...)` in the constructor later executes `import` (of the async module), but maybe you meant it should be imported literally *inside* the constructor, not sure about that.

I hope I better explained myself this time. English isn't my native language and I'm used to work alone most of the time.

**Comment by cdoublev** [comment]
Hello again,

The following change in [`babel-plugin-universal-import/index.js`](https://github.com/faceyspacey/babel-plugin-universal-import/blob/7a9209530d39807b5be3e5f7909133df28e9d1cc/index.js#L208) fixes this HMR issue.

```diff
+ function isUniversalImport(p) {
+   const universalCallee = p.findParent(path => path.node.type === 'CallExpression' && path.node.callee.name === 'universal')
+   if (!universalCallee) return false
+   const program = universalCallee.findParent(path => path.node.type === 'Program')
+   return program.node.body.find(node =>
+     node.type === 'ImportDeclaration'
+       && node.specifiers.find(node => node.type === 'ImportDefaultSpecifier')
+       && node.source.value === 'react-universal-component')
+ }
// ...
      visitor: {
       Import(p) {
         if (p[visited]) return
         p[visited] = true
 
+        if(!isUniversalImport(p)) return
// ...
```

It prevents transforming this:

```js
// src/index.js
import('./notUniversalModule').then(/*...*/))
```

into this:

```js
babel_plugin_universal_import_universalImport__WEBPACK_IMPORTED_MODULE_2___default()({
    id: "./notUniversalModule",
    load: function load() {
        return Promise.all([
            __webpack_require__.e(/*! import() | notUniversalModule */ "notUniversalModule")
                .then(__webpack_require__.bind(null, /*! ./notUniversalModule */ "./src/notUniversalModule.js"))
            ]).then(function (proms) {
                return proms[0];
            });
    },
    path() {
        return path__WEBPACK_IMPORTED_MODULE_1___default.a.join(__dirname, './notUniversalModule');
    },
    resolve() {
        return /*require.resolve*/(/*! ./notUniversalModule*/ "./src/notUniversalModule.js");
    },
    chunkName() {
        return "notUniversalModule";
    }
}).then(/* ... */);
/* WEBPACK VAR INJECTION */}.call(this, "/"))
```

The latter will make `src/notUniversalModule.js` a `module.parents` of `babel-plugin-universal-import/universalImport.js`, which is not wanted, and prevents hot reload of all modules (even the modules wrapped with `universal`) with an `unaccepted update`.

Adding a unit test would involve updating all tests by adding `import universal from 'react-universal-component`. Also note that traversing the tree upwards for each import statement will obviously have a performance impact.

As a reminder, the goal of a dynamic import only client side, not handled by this plugin, is for example loading a polyfill. Its "universal" loading isn't required as it will not change the HTML, and its dynamic loading before running the application (hydration) IS a requirement.

Waiting for your comments.

EDIT: the user could rename the default export of `react-universal-component` to something else than `universal`, therefore my suggested fix should handle this (sorry!).

**Comment by ScriptedAlchemy** [comment]
Can you make a PR?
